# Generated by Django 4.1.3 on 2022-11-18 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargas_Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('horas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dedicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.IntegerField()),
                ('DNI', models.IntegerField()),
                ('legajo', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo_Electivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('desde', models.DateField()),
                ('hasta', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('documento', models.ImageField(upload_to='pdf')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad_Dedicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_minimas', models.IntegerField()),
                ('horas_maximas', models.IntegerField()),
                ('id_dedicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.dedicacion')),
                ('id_modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.modalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('id_carrera', models.ManyToManyField(to='App.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Franja_Horaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dia', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.docente')),
                ('id_instituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.instituto')),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('id_franja_horaria', models.ManyToManyField(to='App.franja_horaria')),
                ('id_localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.localidad')),
                ('id_materia', models.ManyToManyField(to='App.materia')),
                ('id_periodo_electivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.periodo_electivo')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='id_instituto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.instituto'),
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cargas_extras', models.ManyToManyField(to='App.cargas_extras')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.categoria')),
                ('id_dedicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.dedicacion')),
                ('id_dependencia_desempeno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_desmpeno', to='App.instituto')),
                ('id_dependencia_designacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_designacion', to='App.instituto')),
                ('id_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.docente')),
                ('id_franja_horaria', models.ManyToManyField(to='App.franja_horaria')),
                ('id_resolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.resolucion')),
            ],
        ),
    ]
