# Generated by Django 4.1.7 on 2023-03-11 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SgaAsignaciones',
            fields=[
                ('asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_finalizacion', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sga_asignaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaComisiones',
            fields=[
                ('comision', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sga_comisiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaElementos',
            fields=[
                ('elemento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sga_elementos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaPlanes',
            fields=[
                ('plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sga_planes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaUbicaciones',
            fields=[
                ('ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sga_ubicaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShaComisionesBH',
            fields=[
                ('banda_horaria', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sga_comisiones_bh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('desc_categ', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dedicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_dedic', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('legajo', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_documento', models.IntegerField(unique=True)),
                ('nombre_apellido', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(default=None, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_modal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('documento', models.ImageField(upload_to='pdf')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_extra', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SgaComisionesPropuestas',
            fields=[
                ('comision', models.OneToOneField(db_column='comision', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='App.sgacomisiones')),
            ],
            options={
                'db_table': 'sga_comisiones_propuestas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modalidad_Dedicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriccion_horas_minimas', models.IntegerField(default=None, null=True)),
                ('restriccion_horas_maximas', models.IntegerField(default=None, null=True)),
                ('dedicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.dedicacion')),
                ('modalidad', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.modalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Comision_Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.carrera')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.comision')),
            ],
        ),
        migrations.AddField(
            model_name='comision',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.localidad'),
        ),
        migrations.AddField(
            model_name='comision',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.materia'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='instituto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.instituto'),
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('nro_cargo', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_alta', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.categoria')),
                ('dependencia_desempeno', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_desmpeno', to='App.instituto')),
                ('dependencia_designacion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_designacion', to='App.instituto')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.docente')),
                ('modalidad_dedicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.modalidad_dedicacion')),
                ('resolucion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.resolucion')),
            ],
        ),
        migrations.CreateModel(
            name='Carga_Horaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.CharField(max_length=100)),
                ('fecha_hasta', models.CharField(max_length=100)),
                ('hora_inicio', models.CharField(max_length=100)),
                ('hora_finalizacion', models.CharField(max_length=100)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.cargo')),
                ('comision', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.comision')),
                ('tipo_extra', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.tipo_extra')),
            ],
        ),
    ]
