# Generated by Django 4.1.7 on 2023-02-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='fecha_jubilacion',
        ),
    ]
