# Generated by Django 4.1.7 on 2023-02-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_docente_apellido_remove_docente_fecha_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='nombre_apellido',
            field=models.CharField(max_length=255),
        ),
    ]
