# Generated by Django 4.1.7 on 2023-03-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_carrera_nombre_alter_categoria_desc_categ_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SgaPropuestas',
            fields=[
                ('propuesta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_abreviado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sga_propuestas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaPropuestasRa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sga_propuestas_ra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SgaResponsablesAcademicas',
            fields=[
                ('responsable_academica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'sga_responsables_academicas',
                'managed': False,
            },
        ),
        migrations.RenameModel(
            old_name='Localidad',
            new_name='Ubicacion',
        ),
        migrations.DeleteModel(
            name='SgaPlanes',
        ),
        migrations.RenameField(
            model_name='comision',
            old_name='localidad',
            new_name='ubicacion',
        ),
    ]
