# Generated by Django 4.1.7 on 2023-03-25 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_sgapropuestas_sgapropuestasra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SgaComisionesBH',
            fields=[
                ('banda_horaria', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'sga_comisiones_bh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='sgaDocentes',
            fields=[
                ('docente', models.AutoField(primary_key=True, serialize=False)),
                ('legajo', models.IntegerField()),
            ],
            options={
                'db_table': 'sga_docentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='sgaDocentesComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sga_docentes_comision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrera_Instituto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.carrera')),
                ('instituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.instituto')),
            ],
        ),
        migrations.DeleteModel(
            name='ShaComisionesBH',
        ),
    ]
