# Generated by Django 4.1.7 on 2023-03-03 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_cargo_cargo_id_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalidad_dedicacion',
            name='horas_maximas',
        ),
        migrations.RemoveField(
            model_name='modalidad_dedicacion',
            name='horas_minimas',
        ),
        migrations.AddField(
            model_name='modalidad_dedicacion',
            name='restriccion_horas_maximas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='modalidad_dedicacion',
            name='restriccion_horas_minimas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='id_dependencia_desempeno',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_desmpeno', to='App.instituto'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='id_dependencia_designacion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargo_designacion', to='App.instituto'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='id_resolucion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.resolucion'),
        ),
    ]
