# Generated by Django 4.1.7 on 2023-03-25 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_sgacomisionesbh_sgadocentes_sgadocentescomision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='instituto',
        ),
    ]
