# Generated by Django 4.1.7 on 2023-03-25 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_carrera_instituto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia_Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.carrera')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.materia')),
            ],
        ),
    ]
