# Generated by Django 4.1.7 on 2023-03-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_modalidad_dedicacion_horas_maximas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='id_cargo_carga_extra',
            field=models.ManyToManyField(default=None, to='App.cargas_extras'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='id_cargo_franja_horaria',
            field=models.ManyToManyField(default=None, to='App.franja_horaria'),
        ),
    ]
