# Generated by Django 4.1.7 on 2023-03-04 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_cargo_id_cargo_carga_extra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='id_cargo_carga_extra',
            new_name='carga_extra',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='id_categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='id_dependencia_desempeno',
            new_name='dependencia_desempeno',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='id_dependencia_designacion',
            new_name='dependencia_designacion',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='legajo',
            new_name='docente',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='id_cargo_franja_horaria',
            new_name='franja_horaria',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='id_modalidad_dedicacion',
            new_name='modalidad_dedicacion',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='id_cargo',
            new_name='nro_cargo',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='id_resolucion',
            new_name='resolucion',
        ),
        migrations.RenameField(
            model_name='carrera',
            old_name='id_instituto',
            new_name='instituto',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='id_categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='desc_categ',
        ),
        migrations.RenameField(
            model_name='comision',
            old_name='id_franja_horaria',
            new_name='franja_horaria',
        ),
        migrations.RenameField(
            model_name='comision',
            old_name='id_localidad',
            new_name='localidad',
        ),
        migrations.RenameField(
            model_name='comision',
            old_name='id_materia',
            new_name='materia',
        ),
        migrations.RenameField(
            model_name='comision',
            old_name='id_periodo_electivo',
            new_name='periodo_electivo',
        ),
        migrations.RenameField(
            model_name='dedicacion',
            old_name='nombre',
            new_name='desc_dedic',
        ),
        migrations.RenameField(
            model_name='materia',
            old_name='id_carrera',
            new_name='carrera',
        ),
        migrations.RenameField(
            model_name='modalidad',
            old_name='nombre',
            new_name='desc_modal',
        ),
        migrations.RenameField(
            model_name='modalidad_dedicacion',
            old_name='id_dedicacion',
            new_name='dedicacion',
        ),
        migrations.RemoveField(
            model_name='modalidad_dedicacion',
            name='id_modalidad',
        ),
        migrations.AddField(
            model_name='modalidad_dedicacion',
            name='modalidad',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.modalidad'),
        ),
        migrations.AlterField(
            model_name='modalidad_dedicacion',
            name='restriccion_horas_maximas',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='modalidad_dedicacion',
            name='restriccion_horas_minimas',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
