# Generated by Django 4.1.7 on 2023-07-18 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_materia_carrera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='modalidad_dedicacion',
        ),
        migrations.AddField(
            model_name='cargo',
            name='dedicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.dedicacion'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='modalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.modalidad'),
        ),
        migrations.DeleteModel(
            name='Modalidad_Dedicacion',
        ),
    ]
