# Generated by Django 4.1.7 on 2023-07-21 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_remove_cargo_modalidad_dedicacion_cargo_dedicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='activo',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0, message='El valor debe ser 0 o 1.'), django.core.validators.MaxValueValidator(1, message='El valor debe ser 0 o 1.')]),
            preserve_default=False,
        ),
    ]
