# Generated by Django 4.1.7 on 2023-03-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_rename_id_cargo_carga_extra_cargo_carga_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
