# Generated by Django 4.1.7 on 2023-08-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_cargo_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='resolucion',
        ),
        migrations.DeleteModel(
            name='Resolucion',
        ),
    ]
