# Generated by Django 4.1.7 on 2023-03-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_cargo_fecha_baja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='codigo',
        ),
    ]
