# Generated by Django 4.1.7 on 2023-03-08 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_rename_categoria_categoria_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo_Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.cargo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.materia')),
            ],
        ),
    ]
