# Generated by Django 4.1.7 on 2023-08-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_remove_cargo_resolucion_delete_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='resolucion',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
