# Generated by Django 4.1.7 on 2023-08-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_cargo_resolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='resolucion',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
