# Generated by Django 4.1.7 on 2023-03-09 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_cargo_materia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga_Horaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.CharField()),
                ('fecha_hasta', models.CharField()),
                ('hora_inicio', models.CharField()),
                ('hora_finalizacion', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_extra', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='franja_horaria',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='carga_extra',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='franja_horaria',
        ),
        migrations.RemoveField(
            model_name='comision',
            name='franja_horaria',
        ),
        migrations.RemoveField(
            model_name='comision',
            name='periodo_electivo',
        ),
        migrations.DeleteModel(
            name='Cargas_Extras',
        ),
        migrations.DeleteModel(
            name='Franja_Horaria',
        ),
        migrations.DeleteModel(
            name='Periodo_Electivo',
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
        migrations.AddField(
            model_name='carga_horaria',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.cargo'),
        ),
        migrations.AddField(
            model_name='carga_horaria',
            name='comision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.comision'),
        ),
        migrations.AddField(
            model_name='carga_horaria',
            name='tipo_extra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.tipo_extra'),
        ),
    ]
