# Generated by Django 4.1.7 on 2023-08-07 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_cargo_resolucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.CharField(max_length=5)),
                ('hora_fin', models.CharField(max_length=5)),
                ('dia_semana', models.CharField(max_length=25)),
                ('fecha_desde', models.CharField(max_length=10)),
                ('fecha_hasta', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo_CH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.aux')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Comision_CH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.aux')),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.comision')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Extra_CH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.aux')),
                ('tipo_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.tipo_extra')),
            ],
        ),
        migrations.DeleteModel(
            name='Carga_Horaria',
        ),
    ]
