# Generated by Django 4.1.7 on 2023-03-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_carga_horaria_tipo_extra_remove_franja_horaria_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga_horaria',
            name='fecha_desde',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carga_horaria',
            name='fecha_hasta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carga_horaria',
            name='hora_finalizacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carga_horaria',
            name='hora_inicio',
            field=models.CharField(max_length=100),
        ),
    ]
