# Generated by Django 4.1.7 on 2023-08-07 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_aux_cargo_ch_comision_ch_tipo_extra_ch_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aux',
            new_name='Carga_Horaria',
        ),
        migrations.RenameField(
            model_name='cargo_ch',
            old_name='Aux',
            new_name='Carga_Horaria',
        ),
        migrations.RenameField(
            model_name='comision_ch',
            old_name='Aux',
            new_name='Carga_Horaria',
        ),
        migrations.RenameField(
            model_name='tipo_extra_ch',
            old_name='Aux',
            new_name='Carga_Horaria',
        ),
    ]
