# Generated by Django 4.1.7 on 2023-08-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_rename_aux_carga_horaria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo_ch',
            old_name='Carga_Horaria',
            new_name='carga_Horaria',
        ),
        migrations.RenameField(
            model_name='comision_ch',
            old_name='Carga_Horaria',
            new_name='carga_Horaria',
        ),
        migrations.RenameField(
            model_name='tipo_extra_ch',
            old_name='Carga_Horaria',
            new_name='carga_Horaria',
        ),
        migrations.AlterField(
            model_name='carga_horaria',
            name='hora_fin',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='carga_horaria',
            name='hora_inicio',
            field=models.CharField(max_length=8),
        ),
    ]
