# Generated by Django 4.1.7 on 2023-08-11 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_rename_carga_horaria_cargo_ch_carga_horaria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cargo_CH',
            new_name='Cargo_Comision_CH',
        ),
        migrations.RemoveField(
            model_name='cargo_comision_ch',
            name='carga_horaria',
        ),
        migrations.AddField(
            model_name='cargo_comision_ch',
            name='comision_ch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App.comision_ch'),
            preserve_default=False,
        ),
    ]
