# Generated by Django 4.1.7 on 2023-08-11 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_rename_cargo_ch_cargo_comision_ch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo_CT_CH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.cargo')),
                ('comision_ch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.comision_ch')),
                ('tipo_extra_ch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.tipo_extra_ch')),
            ],
        ),
        migrations.DeleteModel(
            name='Cargo_Comision_CH',
        ),
    ]
