# Generated by Django 4.1.7 on 2023-08-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_cargo_ct_ch_delete_cargo_comision_ch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cargo_CT_CH',
            new_name='Cargo_CTE_CH',
        ),
    ]
