# Generated by Django 4.1.7 on 2023-08-12 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_rename_cargo_ct_ch_cargo_cte_ch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga_horaria',
            name='fecha_desde',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='carga_horaria',
            name='fecha_hasta',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='carga_horaria',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='carga_horaria',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='cargo_cte_ch',
            name='comision_ch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.comision_ch'),
        ),
        migrations.AlterField(
            model_name='cargo_cte_ch',
            name='tipo_extra_ch',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.tipo_extra_ch'),
        ),
    ]
