# Generated by Django 4.1.7 on 2023-09-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_alter_carga_horaria_fecha_desde_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comision_Carrera',
        ),
    ]
