# Generated by Django 4.1.7 on 2023-09-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_delete_comision_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_extra_ch',
            name='cant_horas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipo_extra_ch',
            name='fecha_desde',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='tipo_extra_ch',
            name='fecha_hasta',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
