# Generated by Django 4.1.7 on 2023-09-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_tipo_extra_ch_cant_horas_tipo_extra_ch_fecha_desde_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipo_extra_ch',
            name='carga_horaria',
        ),
    ]
