# Generated by Django 4.1.7 on 2023-09-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_remove_tipo_extra_ch_carga_horaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_extra_ch',
            name='cant_horas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tipo_extra_ch',
            name='fecha_desde',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tipo_extra_ch',
            name='fecha_hasta',
            field=models.DateField(),
        ),
    ]
