# Generated by Django 4.1.7 on 2023-09-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_comision_ch_tipo_dictado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='carga_actual',
            field=models.FloatField(default=0.0),
        ),
    ]
