# Generated by Django 4.1.7 on 2023-09-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_cargo_carga_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_extra_ch',
            name='cant_horas',
            field=models.FloatField(),
        ),
    ]
